N_HOSTS=2

NODE1_PCI=${HOST1_PCI}
NODE2_PCI=${HOST2_PCI}

NODE1_MAC=${HOST1_MAC}
NODE2_MAC=${HOST2_MAC}

NODE1_HAS_HW_CKSUM=${HOST1_HAS_HW_CKSUM}
NODE2_HAS_HW_CKSUM=${HOST2_HAS_HW_CKSUM}

SSH1="ssh ${HOST1} source /tmp/devshell &&"
SSH2="ssh ${HOST2} source /tmp/devshell &&"
